### ISSUE TITLE
Sample feedback and Sequence diagram

### ISSUE THREAD

**Issue by rivkode** [line/abc-user-feedback#233]
Now, I'm trying to use this service and I think this could be helpful to handle user-feedback.

It would be better if the two below were added.

1. Function to generate example feedback on its own before connecting Jira.

This is because it could be helpful to users easily test it before using it in earnest.
I believe "easy/simple" is powerful.

Here's an example. These are on the Settings tab.

![image](https://github.com/line/abc-user-feedback/assets/109144975/6268b970-6cbc-45a8-a010-1b0792c0b9b3)

2. Sequence diagram for the main functions or Overall system architecture.

This is to better understand this service.

**Comment by YoungjaeKim** [comment]
Thanks for your feedback :) Let us improve documentation and give some testable experience for better Jira integration.

**Comment by h4l-yup** [comment]
@rivkode 

<img width="1895" alt="image" src="https://github.com/line/abc-user-feedback/assets/28913065/3b3b62b9-1532-41f4-b85e-774375a55371">

With this 'feedback request' button, you can get simple curl to create sample feedback.

It might be helpful for your situation.

**Comment by rivkode** [comment]
It would be helpful !

Thank you for your help :)
