### ISSUE TITLE
Frontend: "yarn dev" Unhandled Runtime Error

### ISSUE THREAD

**Issue by zaanposni** [line/abc-user-feedback#43]
I tried to setup up my own local development instance to fix a few bugs I discovered.
However, after doing `yarn install` and `yarn dev` I was not able to get the frontend working.

npm: 8.19.3
node: 18.13.0
yarn: 1.22.19

I have never worked with react/next/yarn before, but I tried to follow the readme as close as possible

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
``` 
![image](https://github.com/line/abc-user-feedback/assets/24491035/4cb1322e-ddd3-4db1-9bae-a69a507a7102)

```
web:dev: Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
web:dev: 
web:dev: Check your code at _app.tsx:59.
web:dev:     at App (webpack-internal:///./src/pages/_app.tsx:52:16)
web:dev:     at I18nextProvider (/home/myuser/dev/abc-user-feedback/node_modules/react-i18next/dist/commonjs/I18nextProvider.js:13:19)
web:dev:     at AppWithTranslation (/home/myuser/dev/abc-user-feedback/node_modules/next-i18next/dist/commonjs/appWithTranslation.js:59:22)
web:dev:     at StyleRegistry (/home/myuser/dev/abc-user-feedback/node_modules/styled-jsx/dist/index/index.js:449:36)
web:dev:     at PathnameContextProviderAdapter (/home/myuser/dev/abc-user-feedback/node_modules/next/dist/shared/lib/router/adapters.js:78:11)
web:dev:     at AppContainer (/home/myuser/dev/abc-user-feedback/node_modules/next/dist/server/render.js:337:29)
web:dev:     at AppContainerWithIsomorphicFiberStructure (/home/myuser/dev/abc-user-feedback/node_modules/next/dist/server/render.js:373:57)
web:dev:     at div
web:dev:     at Body (/home/myuser/dev/abc-user-feedback/node_modules/next/dist/server/render.js:673:21)
web:dev: Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports
```

**Comment by h4l-yup** [comment]
@zaanposni 

I am sorry for inconvenience and lack of documentation.

Before you run the web project, you should build two packages first: `ufb-tailwind` and `ufb-ui`which are packages for the front-end web page.

You can build the two packages by command `yarn build` and you should build those packages in order. (tailwind - ui)

**Comment by zaanposni** [comment]
Yes that seems to work.
Will have to learn react a bit before I can make a contribution.

I tried to fix a bug in the api key view. When you press the copy button it actually copies the key to the clipboard twice and sends two toast notifications.

Upon investigation in `APIKeySetting.tsx` I found that there are actually two onClick handlers registered. But no matter what I changed. Once I edited a few lines the toasts would just stop showing at all so I have no way of actually confirming that my code works :smile: 

Anyways, thats on me. I will try to contribute a few things here and there once I get everything working. 
Since you mentioned that you guys are actually using an internal issue tracker: Thats fine. My guess is that you would get more interactions and contributions on this repository if you sync them here or at least move some "easy" issues to github that you are willing to outsource to open source contributors. When I find a repository that I am willing to contribute, I often look for the "Good first issue" label. That like a best practice in GitHub.

**Comment by h4l-yup** [comment]
I identified the API Key bug and mentioned it to our front-end developer, @chiol.
For your information, I work on the backend and he works on the frontend, and I don't know react much.
We have a designer and a PM on the team, so there are four of us.

In fact, we hadn't yet had a detailed discussion about how we should manage open source issues and our internal issue tracking tool would work together.
Our stance was that we would think about it when we had open source users, and the time came sooner than we thought. 😄 

We have a meeting next Monday to discuss this, and I think what you're describing (using GitHub to manage issues to be outsourced to open source contributors) is a good approach.

However, there is also a roadmap that we made internally for this product, so it would be great if we could share that as well on this open source, and we'll discuss that as well.

If you have any thoughts on how to share the roadmap, let me know and I'll discuss it with the team.

**Comment by zaanposni** [comment]
Since Microsoft bought GitHub, there have been several improvements to the issue planning system on GitHub.
The feature you are looking for is [GitHub Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects). It is not as powerful as Jira or similar but it gets the job done. 

Many big repositories actually use this very feature to plan releases/sprints or share roadmaps:
- [GitHub](https://github.com/orgs/github/projects/4247)
- [nektos/act](https://github.com/nektos/act/projects/1)
- [Cypress](https://github.com/orgs/cypress-io/projects/13/views/1)

Also there is [GitHub Discussion](https://docs.github.com/en/discussions).

Anyway, I am closing this issue since the original bug has been resolved.
Good luck and have fun to you and your team :)
